[package]
name = "nevermind"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
axum = "0.7.7"
clap = { version = "4.5.20", features = ["derive", "env"] }
dotenvy = "0.15.7"
reqwest = { version = "0.12.8", features = ["json"] }
secrecy = { version = "0.10.2", features = ["serde"] }
tokio = { version = "1.40.0", features = ["full"] }
