services:
  postgres:
    image: postgres:latest
    container_name: postgres-latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-latest
    ports:
      - "6379:6379"
      - "8001:8001" # Redis Insight web interface
